name: Release

on:
  push:
    branches:
      - master

jobs:

  prepare_version:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.current-day.outputs.formattedTime }}

    steps:
      - name: Prepare version number using current day
        uses: 1466587594/get-current-time@v2.0.0
        id: current-day
        with:
          format: YYYY.MM.DD

  build_packages:
    runs-on: ubuntu-latest
    needs: prepare_version

    steps:

      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Build packages
        run: ./bin/dist v${{ needs.prepare_version.outputs.version }}

      - name: Upload packages as artifacts
        uses: actions/upload-artifact@v1
        with:
          name: pkg
          path: pkg

  create_release:
    runs-on: ubuntu-latest
    needs: prepare_version

    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

    steps:

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.prepare_version.outputs.version }}
          release_name: v${{ needs.prepare_version.outputs.version }}

  upload_assets:
    runs-on: ubuntu-latest
    needs: [ prepare_version, build_packages, create_release ]

    strategy:
      matrix:
        os_arch:
          - darwin_amd64
          - darwin_386
          - linux_386
          - linux_amd64
          - linux_arm
          - windows_386
          - windows_amd64

    steps:

      - name: Download packages from artifacts
        uses: actions/download-artifact@v1
        with:
          name: pkg

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: pkg/terraform-inventory_v${{ needs.prepare_version.outputs.version }}_${{ matrix.os_arch }}.zip
          asset_name: terraform-inventory_v${{ needs.prepare_version.outputs.version }}_${{ matrix.os_arch }}.zip
          asset_content_type: application/zip
